version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin
      
      # Variables Setup
      - IMAGE_REPO_NAME="app-online-shop"
      - IMAGE_NAME="$DOCKER_REGISTRY_USERNAME/$IMAGE_REPO_NAME"
      
      # Versioning Logic (v1, v2, v3...)
      - VERSION_TAG="v$CODEBUILD_BUILD_NUMBER"
      - echo "Current Version Tag is $VERSION_TAG"

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image with dual tags...
      # Aik hi image ko do tags dena: Aik versioned aur aik latest
      - docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION_TAG .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing images to Docker Hub...
      # Dono tags push karna zaroori hai
      - docker push $IMAGE_NAME:latest
      - docker push $IMAGE_NAME:$VERSION_TAG
      
      - echo Packaging application for Deployment...
      - zip -r online-shop-app.zip * .[^.]* -x "node_modules/*" ".git/*"
      - aws s3 cp online-shop-app.zip s3://aws-s3-bucket-ci-cd/online-shop-app/
      
      - echo Writing image definitions file...
      # Image URI mein Versioned Tag use karein taake track rahay
      - printf '[{"name":"online-shop-container","imageUri":"%s"}]' $IMAGE_NAME:$VERSION_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - '**/*-app.zip'
    - 'imagedefinitions.json'
    - 'appspec.yml'
    - 'scripts/**/*'
  discard-paths: no
